### ISSUE TITLE
admob plugin not ready error

### ISSUE THREAD

**Issue by YooJaSung** [floatinghotpot/cordova-plugin-admob#182]
hi~ now iam using your cordova-plugin-admob. 

after applicaiton exit using android hardware backbutton, and re running application

admob plugin not ready alert show and my application view did not show.. 

i added error screen shot! 

how can i solve this problem??
![1423551763655](https://cloud.githubusercontent.com/assets/6368241/6122969/0901a330-b13f-11e4-825a-504ebb776acb.jpeg)
![1423551765285](https://cloud.githubusercontent.com/assets/6368241/6122971/0d06baba-b13f-11e4-86b6-028c1a5e0fff.jpeg)

**Comment by floatinghotpot** [comment]
I cannot reproduce your problem, but I personally recommend you to use the pro version, which is improved a lot, see: 
https://github.com/floatinghotpot/cordova-admob-pro

**Comment by YooJaSung** [comment]
oh thank you,, i didn't know cordova-admob-pro ..! thank you again!
