### ISSUE TITLE
Execution failed for task ':compileArmv7DebugJava'.

### ISSUE THREAD

**Issue by ibewugb** [floatinghotpot/cordova-plugin-admob#183]
I'm getting the following error while building my Android Project:

:compileArmv7DebugJava/Users/user/App/platforms/android/src/com/rjfun/cordova/plugin/AdMob.java:219: error: cannot find symbol
                    ((ViewGroup) webView.getRootView()).addView(adViewLayout, params);
                                        ^
  symbol:   method getRootView()
  location: variable webView of type CordovaWebView
/Users/user/App/platforms/android/src/com/rjfun/cordova/plugin/AdMob.java:411: error: cannot find symbol
                        ViewGroup parentView = (ViewGroup) webView.getParent();
                                                                  ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.691 secs

/Users/user/App/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/user/App/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/user/App/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/user/App/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project

**Comment by floatinghotpot** [comment]
I think the new version Cordova has changed the web view interface, will find time to fix it.

**Comment by ibewugb** [comment]
Could be, because I updated today to Cordova 4.2.0

**Comment by floatinghotpot** [comment]
before I find time to fix it, maybe you can try the pro version.

as in pro version I already fix this issue to support Cordova 4.x months ago, and it's enhanced with more features.

https://github.com/floatinghotpot/cordova-admob-pro

**Comment by manfromshadow** [comment]
I can confirm this issue too.

**Comment by heliojff** [comment]
I updated to Cordova 5.0 and had a problem with the admob pro. Error: cannot find symbol layout :(

**Comment by floatinghotpot** [comment]
can you paste the logs?
