### ISSUE TITLE
[Cordova 4.0] Fail to build app with admob plugin

### ISSUE THREAD

**Issue by haoxli** [floatinghotpot/cordova-plugin-admob#186]
There is error thrown when build admob app with admob plugin in Cordova 4.0
Steps:
1. Clone cordova 4.0
`$ git clone https://github.com/apache/cordova-android.git`
2. Create project
```
$ cd cordova-android
$ ./bin/create HelloWorld org.crosswalkproject.sample HelloWorld
$ cd HelloWorld
$ plugman install --platform android --project . --plugin /path/to/cordova-plugin-admob
```
3. Build app
```
$ cd HelloWorld
$ ./cordova/build
```

Fail to build app becasue error occurs:
```
:compileArmv7DebugJava
/tmp/b1o6dtxh95h78bj/cordova/tct_2dtransforms_css3_tests/src/com/rjfun/cordova/plugin/AdMob.java:219: error: cannot find symbol
                    ((ViewGroup) webView.getRootView()).addView(adViewLayout, params);
                                        ^
  symbol:   method getRootView()
  location: variable webView of type CordovaWebView
/tmp/b1o6dtxh95h78bj/cordova/tct_2dtransforms_css3_tests/src/com/rjfun/cordova/plugin/AdMob.java:411: error: cannot find symbol
                        ViewGroup parentView = (ViewGroup) webView.getParent();
                                                                  ^
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by floatinghotpot** [comment]
Please use the pro version:

https://github.com/floatinghotpot/cordova-admob-pro

**Comment by haoxli** [comment]
Thanks for your comment, it build successful in Crodova 4.0, but the admob test run fail with cordova-admob-pro, which run pass in cordova 3.6 with old plugin.
My tests is https://github.com/haoxli/crosswalk-test-suite/commit/251dde5d189cf33a06c710b1c90d75d14abe087a#diff-3a63f95b87e5c965fd5ab1f0f204ed29
Does there any different usage in the two admob plugin?

**Comment by haoxli** [comment]
hi @floatinghotpot  Any update?

**Comment by floatinghotpot** [comment]
cordova team has changed the code a lot in cordova-android 4.0 (cordova CLI v5.0), so the plugin won't work with it.

If you are using cordova CLI 5.0, please migrate to cordova-plugin-admobpro
If you are using cordova CLI 4.x, may use com.google.cordova.admob

see the example code here:
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/test/index.html

**Comment by floatinghotpot** [comment]
I can try forking your repo of test suite, and send a pull request later ...

**Comment by floatinghotpot** [comment]
i've forked your repo and add admob to use case, please review and merge, thanks.

**Comment by haoxli** [comment]
Thank you very much. I will submit it to crosswalk-project/crosswalk-test-suite after verification.
