### ISSUE TITLE
Ads Display in Middle of Screen in Cordova Android 4.0.0

### ISSUE THREAD

**Issue by RangerRick** [floatinghotpot/cordova-plugin-admob#188]
I recently updated my project to the latest Cordova and associated platforms and plugins.  In Android (4.2, also reported on 4.1, probably others), the ad banner now shows in the middle of the screen instead of the bottom:

![screen shot 2015-04-30 at 6 14 24 pm](https://cloud.githubusercontent.com/assets/89252/7423638/0c37d876-ef65-11e4-9671-9368ec0d890c.PNG)

If I downgrade to Cordova Android 3.7.1 and leave all of my code alone, it works:

![screen shot 2015-04-30 at 6 19 44 pm](https://cloud.githubusercontent.com/assets/89252/7423668/7db081ba-ef65-11e4-83a7-1dbab0ab95d1.PNG)

**Comment by floatinghotpot** [comment]
Please consider using the pro version, it's update more frequently and much powerful.
https://github.com/floatinghotpot/cordova-admob-pro

**Comment by RangerRick** [comment]
Actually I am using the pro version, guess I just found the wrong github repo when I was looking for where to open an issue.  I'll reopen the issue there.

**Comment by RangerRick** [comment]
https://github.com/floatinghotpot/cordova-admob-pro/issues/119
