### ISSUE TITLE
Support for Cordova 4.0

### ISSUE THREAD

**Issue by frostyelkarne** [floatinghotpot/cordova-plugin-admob#190]
Will this plugin support Cordova 4.0 or will it stay on Cordova 3.5? I need to know the strategy so I can update my documentation for my Construct 2 plugin.

**Comment by floatinghotpot** [comment]
The totally redesigned pro version is more powerful, and most users have migrated to pro version. This one will not be evolved, so please migrate to pro version.

**Comment by frostyelkarne** [comment]
Ok, thanks for the info. I will update the documentation to refer to the pro version and deprecate this plugin
