### ISSUE TITLE
Percentage based allocation

### ISSUE THREAD

**Issue by chrisschaub** [floatinghotpot/cordova-plugin-admob#193]
So, the old AdMob allowed you to use percentage based allocation of ads, especially for House Ads. The new interface has removed this, more genius from google. Anyway, is there a way to pass an option to your plugin to request an add is filled 100%? This doc goes into it ...

https://code.google.com/p/google-mobile-dev/source/browse/examples/custom-events/src/com/google/example/ads/customevents/impl/PercentageHouseAds.java?repo=examples-android

The use-case is to only show house ads, never a mediated ad. Thanks for any suggestions.

**Comment by floatinghotpot** [comment]
to show house ads, you can use the [admob plugin pro version](https://github.com/floatinghotpot/cordova-admob-pro), and set ad unit id to your google DFP (doubleclick for publisher).

**Comment by chrisschaub** [comment]
Thanks, yes, that's exactly what we have done.

On Wed, Jun 10, 2015 at 5:02 AM, Raymond Xie <notifications@github.com>
wrote:

> to show house ads, you can use the admob plugin pro version
> <https://github.com/floatinghotpot/cordova-admob-pro>, and set ad unit id
> to your google DFP (doubleclick for publisher).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-plugin-admob/issues/193#issuecomment-110678691>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com
