### ISSUE TITLE
Does this plugin take 2% of our revenue?

### ISSUE THREAD

**Issue by TakayukiSakai** [floatinghotpot/cordova-plugin-admob#205]
I saw these lines in native codes... (commit: ea33979d6f5e634c40d8cc662c443576c96f2219)

iOS: /src/ios/CDVAdMob.m
```
if(rand()%100 <2) publisherId = DEFAULT_BANNER_ID; // This seems to be this AdMob id for this plugin's owner.
```

Android : /src/android/AdMob.java
```
if((new Random()).nextInt(100) < 2) publisherId = "ca-app-pub-6869992474017983/9375997553"; // So does this.
```

I think this plugin's owner should write about this if he's taking some revenue from developers.

**Comment by abulte** [comment]
Hi, its seems you're pointing to the wrong commit (just a README update). But I agree w/ you: if such a thing is real, plugin's owner should be clear about it...

**Comment by floatinghotpot** [comment]
Please read the term of use and license agreement here:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement

You can simply fork and remove the 2% ad sharing logic, if you pick this open source one.

**Comment by MBuchalik** [comment]
Did I understand it correctly that this plugin now doesn't take away anything from my revenue? In the readme, it says "This project is fully open source, and no ad traffic sharing any more.". Is there any other way this plugin could take some of my views (or user data), or am I completely "safe" now?

**Comment by floatinghotpot** [comment]
Yes, the 2% ad sharing has been removed. You can fork and review the source code.
