### ISSUE TITLE
Conflict with play-game plug-in

### ISSUE THREAD

**Issue by hanrock** [floatinghotpot/cordova-plugin-admob#211]
Hey, i'm trying to use admobpro plugin along with this https://github.com/cranberrygame/cordova-plugin-game and i'm getting this error:
![screenshot_1](https://cloud.githubusercontent.com/assets/7755159/14414724/47e6c238-ff6d-11e5-8a3c-507b0cbb12a4.png)

Thanks.

**Comment by floatinghotpot** [comment]
Try this game center plugin, with 69 stars (the one you use only 8 stars):
https://github.com/leecrossley/cordova-plugin-game-center

**Comment by hanrock** [comment]
Thanks for your fast reply Ray! But i need a plugin for Android platform, and this game Center only supports iOS :(

**Comment by floatinghotpot** [comment]
Check the error message "cannot find symbol", the error is not conflict but by the game plugin you are using. Please report it to the plugin.
