### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by anonrig** [floatinghotpot/cordova-plugin-admob#212]
Fetching plugin "com.google.admobsdk" via npm
Failed to install 'cordova-plugin-admob':CordovaError: Failed to fetch plugin com.google.admobsdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.google.admobsdk

**Comment by floatinghotpot** [comment]
com.google.admobsdk is no more valid, as legacy cordova plugin registry has been phased out, and all plugins have been migrate to npm. 

try this one:
https://github.com/floatinghotpot/cordova-admob-pro

**Comment by anonrig** [comment]
Thanks @floatinghotpot
