### ISSUE TITLE
AdMob undefined

### ISSUE THREAD

**Issue by marmikbhatt** [floatinghotpot/cordova-plugin-admob#220]
I am using Cordova 6.3.1 and Android SDK 24.4.1. I have tried my best to follow the guidelines given by the plugin, but it is not showing banner at all.

So, I decided to use a DOM element as console. and I used try and catch, where in try I added AdMob code. Now I am getting error: AdMob is undefined, while compiling the app it shows no error, but when APK is installed, it shows the error.

I have also added location of AdMob.js file to plugin folder in script tag in my index.html file.

I have also checked that all other Javascript code is running perfectly, even ajax. I have double checked about Banner ID etc...

Help me on these, where I have made mistake???

**Here is my code,**

`var admobid = {};
    logmessage('initializing the advertisement...');
// TODO: replace the following ad units with your own
if( /(android)/i.test(navigator.userAgent) ) { 
  admobid = { // for Android
    banner: 'ca-app-pub-xxxxxxxxxxxxxxxx/zzzzzzzzzzzz',
    interstitial: 'ca-app-pub-xxxxxxxxxxxxxxxx/zzzzzzzzzzzz'
  };
}

function initApp() {
  if (! AdMob ) { logmessage( 'admob plugin not ready' ); return; }
	logmessage('creating banner...');
  // this will create a banner on startup
  AdMob.createBanner( {
    adId: admobid.banner,
    position: AdMob.AD_POSITION.BOTTOM_CENTER,
    isTesting: true, // TODO: remove this line when release
    overlap: false,
    offsetTopBar: false,
    bgColor: 'black',
	autoShow: true
  } );
  logmessage('preparing interstitial...');
  // this will load a full screen ad on startup
  AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    isTesting: true, // TODO: remove this line when release
    autoShow: true
  });
}
//console.clear();
try {
    initApp();
}
catch(e) {
    logmessage(e.name + ': ' + e.message);
}

function logmessage(message){
	document.getElementById('logmessage').innerHTML = message;
}`

**Comment by becvert** [comment]
I think that the option `adId` is not supported.
You should either use `publisherId` (for banners) or `interstitialAdId`

**Comment by marmikbhatt** [comment]
Thanks that was the thing, solved and running
