### ISSUE TITLE
Google play services compatibility.

### ISSUE THREAD

**Issue by cesarlvielma** [floatinghotpot/cordova-plugin-admob#226]
Hi Guys. I was tring to build a cordova app with this two plugins:

https://github.com/floatinghotpot/cordova-plugin-admob/
https://github.com/fechanique/cordova-plugin-fcm

but something is wrong with google services version and i did get this error:

`Error: /home/cesar/Freelancer/gamerchampions/fleek/fleek-main/angular/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.
`

A possible fix that i found was replace in platforms/android/project.properties :

`cordova.system.library.1=com.google.android.gms:play-services-ads:+` 
by
`cordova.system.library.1=com.google.android.gms:play-services-ads:9.2.0`

i am not a plugin developer or something like that, What you think about a better solution for this?

Regards !

**Comment by punksta** [comment]
look at https://github.com/fechanique/cordova-plugin-fcm/issues/214#issuecomment-273771378

**Comment by cesarlvielma** [comment]
Thanks for your reply. I solved it with a FCM fork:
https://github.com/fechanique/cordova-plugin-fcm/issues/179#issuecomment-269886277

**Comment by hishammalik** [comment]
fork solved the problem for me
