### ISSUE TITLE
Show Facebook ads

### ISSUE THREAD

**Issue by remisture** [floatinghotpot/cordova-plugin-admob#227]
Can this plugin show Facebook ads as well, or do I need to use `cordova-admob-pro` together with `cordova-plugin-admob-facebook` to make that work?

**Comment by floatinghotpot** [comment]
no, you need use `cordova-admob-pro` mediation with `cordova-plugin-admob-facebook` to work, to show both admob and facebook ads.

Or, use `cordova-plugin-facebookads` to show facebook audience network ad only.

**Comment by remisture** [comment]
Thank you!
